version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

workflows:
  test:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout
      - run:
          name: Package Setup
          command: |
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: pytest --cov=. --cov-config=./coverage.ini --cov-report=xml:./coverage.xml
      - codecov/upload:
          file: 'coverage.xml'
          token: $CODECOV_TOKEN
