version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

workflows:
  test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout
      - run:
          name: Package Setup
          command: |
            apk update
            apk add curl curl-dev
            apk add bash bash-dev
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: pytest . --cov=. --cov-report=xml:./coverage.xml -c tests/pytest.ini
      - codecov/upload:
          file: 'coverage.xml'
          token: $CODECOV_TOKEN